# Generated by Django 4.2.14 on 2024-07-15 00:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genre',
            name='genre_name_case_insensitive_unique',
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='genre_n_case_insensitive_index'),
        ),
    ]
