# Generated by Django 4.2.14 on 2024-07-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_language_language_name_case_insensitive_unique_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genre',
            name='genre_n_case_insensitive_index',
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(models.F('name'), name='genre_n_case_insensitive_index'),
        ),
    ]
