# Generated by Django 4.2.14 on 2024-07-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_genre_genre_n_case_insensitive_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=200),
        ),
    ]
