# Generated by Django 4.2.14 on 2024-07-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_genre_name_alter_language_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='genre',
            name='genre_n_case_insensitive_index',
        ),
    ]
